plugin:
  name: custom-data-type-tnadiscovery
  version: 1.0
  url: https://github.com/programmfabrik/easydb-custom-data-type-tnadiscovery
  displayname:
    de-DE: tnadiscovery-Verknüpfung
    en-US: tnadiscovery-Referencing
  info:
    de-DE: Stellt Verknüpfungen mit den Discovery-System des National Archive London her.
    en-US: Use for references to entities of the discoverydystem of the National Archive London.
  server:
    api-version:
      require: 1
  webfrontend:
    url: custom-data-type-tnadiscovery.js
    l10n: l10n/
    css: custom-data-type-tnadiscovery.css
custom_types:
  tnadiscovery:
    mapping:
      conceptName:
        type: text
      conceptURI:
        type: text
      discoveryID:
        type: text
      discoveryURL:
        type: text
      referenceNumber:
        type: text
      locationHeld:
        type: text
      title:
        type: text
      description:
        type: text
    config:
      schema:
      mask:
